version: '3.3'

services:
  web:
    build:
      context: ./
    volumes:
      - ./:/code
    ports:
      - "3000:3000"
  web_init:
    build:
      context: ./
      dockerfile: Docker_init
    volumes:
      - ./:/code
    tty: true